routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*
*	Admin Route
*/
Route::prefix('admin')
	->name('admin.')
	->middleware(['role:admin'])
	->group(function() {
		Route::get('/', function(){
			return view('auth.login');
		})
		->name('login')
		->middleware('guest');

		Route::get('/dashboard',[App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard.index');
		Route::resource('users', App\Http\Controllers\Admin\UserController::class)->only([
			'index', 'show','destroy'
		]);
		Route::resource('profile', App\Http\Controllers\Admin\ProfileController::class)->only([
			'create','store'
		]);
		Route::resource('change-password',App\Http\Controllers\Admin\ChangePasswordController::class)->only([
			'index', 'store'
		]);
		Route::resource('agents', App\Http\Controllers\Admin\AgentController::class);

		// Assign user to agent
		Route::get('agents/{user}/assign-user', [App\Http\Controllers\Admin\AssignUserController::class, 'create'])->name('agent-assign-user');
		Route::post('agents/{user}/assign-user/store', [App\Http\Controllers\Admin\AssignUserController::class, 'store'])->name('store-agent-assign-user');
	});

Route::prefix('user')
	->name('user.')
	->middleware(['auth', 'role:user'])
	->group(function() {
		Route::resource('change-password',App\Http\Controllers\User\ChangePasswordController::class)->only([
			'index', 'store'
		]);
		Route::resource('profile', App\Http\Controllers\User\ProfileController::class)->only([
			'create','store'
		]);
		Route::resource('dashboard', App\Http\Controllers\User\DashboardController::class)->only([
			'index'
		]);
		Route::resource('account-settings', App\Http\Controllers\User\AccountSettingController::class)->only([
			'create', 'store'
		]);
		Route::resource('order-preferences', App\Http\Controllers\User\OrderPreferenceController::class)->only([
			'index', 'create' ,'store', 'update', 'edit', 'destroy'
		]);

		Route::resource('address-book-list', App\Http\Controllers\User\AddressBookController::class)->only([
			'index', 'store', 'update', 'edit', 'destroy'
		]);
		
		Route::get('get-states-list', [App\Http\Controllers\User\CountryController::class, 'getStates'])->name('states.list');
		
		Route::get('get-cities-list', [App\Http\Controllers\User\CountryController::class, 'getCities'])->name('cities.list');

		Route::resource('products', App\Http\Controllers\User\ProductController::class)->only([
			'index','store','edit','update'
		]);

		Route::resource('manage-cards', App\Http\Controllers\User\ManageCardController::class)->only([
			'index','store','edit','update'
		]);
		
		Route::delete('order-preference-ref/{id}', [App\Http\Controllers\User\OrderReferenceController::class, 'destroy']);

		Route::delete('order-preference-broker/{id}', [App\Http\Controllers\User\OrderBrokerController::class, 'destroy']);
		
		//Letter
		Route::get('letter-quote/create', [App\Http\Controllers\User\LetterQuoteController::class, 'create'])->name('letter-quote.create');
		Route::post('letter-quote', [App\Http\Controllers\User\LetterQuoteController::class, 'store'])->name('letter-quote.store');

		//PAK
		Route::get('pak-quote/create', [App\Http\Controllers\User\PakQuoteController::class, 'create'])->name('pak-quote.create');
		Route::post('pak-quote', [App\Http\Controllers\User\PakQuoteController::class, 'store'])->name('pak-quote.store');
		
		//PACKAGE
		Route::get('package-quote/create', [App\Http\Controllers\User\PackageController::class, 'create'])->name('package-quote.create');
		Route::post('package-quote', [App\Http\Controllers\User\PackageController::class, 'store'])->name('package-quote.store');

		//Get shipment rates
		Route::post('get-shipment-rates', [App\Http\Controllers\User\ShipmentRateController::class, 'getRates'])->name('shipment-rates');		
		Route::post('set-shipment-rate', [App\Http\Controllers\User\ShipmentRateController::class, 'setShipmentRate'])->name('shipment.set.rate');

		//Checkout
		Route::get('shipment-checkout', [App\Http\Controllers\User\ShipmentRateController::class, 'checkout'])->name('shipment.checkout');
		Route::post('shipment-checkout', [App\Http\Controllers\User\CheckoutController::class, 'store'])->name('checkout');

		//Order Summary page
		Route::get('order-summary/{id}', [App\Http\Controllers\User\OrderController::class, 'show'])->name('order.summary');

		//My Shipemensts List
		Route::get('my-shipments', [App\Http\Controllers\User\MyShipmentController::class, 'index'])->name('my.shipments');
	});

/**
 * Agent routes 
 */
Route::prefix('agent')->name('agent.')->group(function() {
	Route::get('/', function() {
		return view('auth.login');
	})
	->name('login')
	->middleware('guest');

	Route::get('/dashboard',[App\Http\Controllers\Agent\DashboardController::class,'index'])
	->name('dashboard.index')
	->middleware(['auth', 'role:agent']);

	Route::get('/assigned-user',[App\Http\Controllers\Agent\AssignedUserController::class,'index'])
	->name('assigned-user.index')
	->middleware(['auth', 'role:agent']);

	Route::get('/assigned-user/create',[App\Http\Controllers\Agent\AssignedUserController::class,'create'])
	->name('assigned-user.create')
	->middleware(['auth', 'role:agent']);

	Route::post('/assigned-user/store',[App\Http\Controllers\Agent\AssignedUserController::class,'store'])
	->name('store-agent-assign-user')
	->middleware(['auth', 'role:agent']);
});

Route::prefix('agent')->name('agent.')->middleware(['auth', 'role:agent,user'])->group(function() {
	Route::post('/login-as-customer', [App\Http\Controllers\Agent\AssignedUserController::class,'loginAsCustomer'])->name('login-as-customer')->middleware(['auth']);
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/forget-password', function () {
	return view('pages.forget-password');
});

Route::get('/address-book', function () {
	return view('pages.address-book');
});

Route::get('/distributions', function () {
	return view('pages.distributions');
});

Route::get('/add-product', function () {
	return view('pages.add-product');
});

Route::get('/account-settings-page', function () {
	return view('pages.account-settings');
});

Route::get('/home-page', function () {
	return view('pages.home');
});


Route::get('/my-shipment-all', function () {
	return view('pages.my-shipment-all');
});

Route::get('/active-shipment', function () {
	return view('pages.active-shipment');
});

Route::get('/delivered-shipment', function () {
	return view('pages.delivered-shipment');
});

Route::get('/my-quote', function () {
	return view('pages.my-quote');
});

Route::get('/my-quote-list', function () {
	return view('pages.my-quote-list');
});

Route::get('/choose-packaging', function () {
	return view('pages.choose-packaging');
});

Route::get('/letter', function () {
	return view('pages.letter');
});

Route::get('/pak', function () {
	return view('pages.pak');
});

Route::get('/package', function () {
	return view('pages.package');
});

Route::get('/ltl', function () {
	return view('pages.ltl');
});

// Fedex
Route::get('sample-fedex', [App\Http\Controllers\FedExController::class, 'store']);
Route::get('sample-ltl-fedex', [App\Http\Controllers\FedExController::class, 'ltl']);

// Create pending FedEx shipment
Route::get('create-fedex-open-shipment', [App\Http\Controllers\FedExController::class, 'createOpenShipment']);

// UPS get single rate
Route::get('get-ups-rate', [App\Http\Controllers\UpsController::class, 'store']);

// UPS get service rates 
Route::get('get-ups-transit-rate', [App\Http\Controllers\UpsController::class, 'rateTimeInTransit']);

Route::get('create-ups-shipment', [App\Http\Controllers\UpsController::class, 'createShipment']);

// Canada Post rating
Route::get('get-canada-post-rate', [App\Http\Controllers\CanadaPostController::class, 'getRates']);

//Create Quote home page

Route::post('request-quote/create', [App\Http\Controllers\RequestQuoteController::class, 'store'])->name('request.quote.create');

/*
//Courier canpar API demo
// Route::get('courier/canpar-api-tracking', [App\Http\Controllers\CourierApiController::class, 'canparApiCourierTracking']);

//Courier ArcBest API demo
// Route::get('courier/arc-best-api-get-rates', [App\Http\Controllers\CourierApiController::class, 'arcbestapiGetRates']);

//Canada Post API sandbox rates between 2 points
// Route::get('courier/canada-post-api-get-rates-two-points', [App\Http\Controllers\CourierApiController::class, 'canadaPostApiGetRates']);
*/

//AutoComplete city
Route::get('search-cities-suggestions', [App\Http\Controllers\CitySearchController::class, 'searchCity'])->name('autocomplete.city');

//Import Excel
Route::get('import-excel', [App\Http\Controllers\ImportExcelController::class, 'index'])->name('import.list');
Route::post('import-excel', [App\Http\Controllers\ImportExcelController::class, 'store'])->name('import.excel.store');

//Track UPS Shipment
Route::get('track-ups-shipment/{trackId}', [App\Http\Controllers\UpsController::class, 'trackShipment']);
Route::get('cancel-ups-shipment/{shipmentid}', [App\Http\Controllers\UpsController::class, 'cancelShipment']);

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::where([ 
            'role_id' =>2 
        ])->withTrashed()->paginate(15);

        return view('admin.user.index',compact('users'));
    }

    public function show($id)
    {
        $user = User::withTrashed()->find($id);
        return view('admin.user.show',compact('user'));

    }

    public function destroy($id)
    {
        $user = User::withTrashed()->find($id);
        $message='deleted';
        if ($user->trashed()) {
            $user->restore();
            $message='restored';
        } else {
            $user->delete();
        }

        return back()
            ->with('success', "User has been $message successfully.");
    }
}

app/Http/Controllers/User/AccountSettingController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserProfile;
use App\Models\CompanyDetail;
use App\Models\Country;
use App\Models\Language;
use App\Models\Unit;
use App\Models\NotificationSetting;
use App\Models\OrderPreference;
use Illuminate\Support\Facades\Auth;
use App\Models\UserCard;
use App\Models\AccountPayableDetail;
use Stripe\Stripe;
use Stripe\Customer;
use Stripe\Charge;
use Exception;

class AccountSettingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $publishkey = config('app.STRIPE_PUBLISHABLE_KEY');

        $user = User::where(['id' => Auth::user()->id])->first();

        //Country
        $countries = Country::get(['name', 'id']);

        //Languages
        $languages = Language::pluck('title', 'id');

        //Units
        $units = Unit::pluck('title', 'id');

        //Notifications
        $userId = Auth::user()->id;
        
        //Nitification Settings
        $notificationSettings = NotificationSetting::pluck('title', 'id');

        //Order Preferences        
        $orders = OrderPreference::where('user_id', $userId)->get();

        //My Cards
        $myCards = UserCard::where('user_id', Auth::user()->id)->get();

        return view('user.settings.account.create', compact(
            'user', 
            'countries', 
            'units', 
            'languages', 
            'orders', 
            'notificationSettings',
            'publishkey',
            'myCards'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Auth::user()->id;

        $request->validate([
            'first_name' => 'required|string',
            'last_name'  => 'required|string',
            'email'      => 'required|string|unique:users,email,'.$id,
            'phone_number'=> 'required|string',
            'company_name' => 'required|string',
            'address' => 'required|string',
            'postal_code' => 'required|string',
            'company_email' => 'required|string|email',
            'company_phone' => 'required|string',
            'company_country' => 'required',
            'company_state' => 'required',
            'company_city' => 'required|string|max:255',
            'billing_address' => 'required|string|max:255',
            'billing_country' => 'required|string|max:255',
            'billing_state' => 'required|string|max:255',
            'billing_city' => 'required|string|max:255',
            'billing_postal_code' => 'required|string|max:255',
            'billing_email' => 'required|string|max:255',
            'billing_phone' => 'required|string|max:255',
            'contact_name' => 'required|string',
            'account_payable_email' => 'required|string|email',
            'account_payable_phone' => 'required|string',
            'payment_terms' => 'required|string'
        ]);

        $input = $request->all();

        $user = User::find($id);

        $user->email = $input['email'];

        $user->save();

        //Profile
        $user->profile()->updateOrCreate(['user_id' => $id], [
            'first_name' => $input['first_name'],
            'last_name' => $input['last_name'],
            'phone_no' => $input['full_phone'],
        ]);

        //Account Payable Details
        $user->accountPayableDetail()->updateOrCreate(['user_id' => $id], [
            'contact_name' => $input['contact_name'],
            'email' => $input['account_payable_email'],
            'phone' => $input['account_payable_phone'],
            'payment_terms' => $input['payment_terms'],
            'is_prepaid' => (int) $request->has('is_prepaid'),
            'is_same_main_contact' => (int) $request->has('is_same_main_contact'),
        ]);

        //Billing Address
        $user->billingAddress()->updateOrCreate(['user_id' => $id], [
            'address' => $input['billing_address'],
            'country' => $input['billing_country'],
            'state' => $input['billing_state'],
            'city' => $input['billing_city'],
            'postal_code' => $input['billing_postal_code'],
            'email' => $input['billing_email'],
            'phone_no' => $input['billing_phone'],
        ]);

        //Company Information
        $user->companyDetail()->updateOrCreate(['user_id' => $id], [
            'company_name' => $input['company_name'],
            'address' => $input['address'],
            'postal_code' => $input['postal_code'],
            'email' => $input['company_email'],
            'phone_no' => $input['company_phone'],
            'country_id' => $input['company_country'],
            'state_id' => $input['company_state'],
            'city' => $input['company_city'],
            'is_bill_same' => (int) $request->has('is_bill_same')
        ]);

        //Notification Settings
        $user->notificationSettings()->sync($request->notificationSettings);

        return redirect()->back()->with('message', "Account settings has been updated successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.dashboard.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
}

resources/views/user/my-shipments/index.blade.php
@extends('layouts.dashboard')
@section('title', 'My Shipments')
@section('content')

<div class="center-navbar">
    <ul>
        <li class="active"><a href="{{ route('user.my.shipments') }}">All</a></li>
        <li><a href="/active-shipment">Active Shipment</a></li>
        <li><a href="/delivered-shipment">Delivered</a></li>
    </ul>
</div>
<div class="content">
    <div class="search-container bg-white shadow-sm p-4 mb-5">
        <form action="#">
            <div class="row">
                <div class="col-3">
                    <div class="form-group">
                        <div class="search-outer search-location">                            
                            <input type="text" name="city_from" placeholder="City From" class="form-control light-placeholder custom-text-input" value="{{ $request->query('city_from') }}">
                        </div>
                    </div>
                </div>
                 <div class="col-3">
                    <div class="form-group">
                        <div class="search-outer search-location">                            
                            <input type="text" name="city_to" placeholder="City To" class="form-control light-placeholder custom-text-input" value="{{ $request->query('city_to') }}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="form-group">
                        <label>Date From</label>
                        <div class="calender-outer">
                            <img class="user-img" src="{{ asset('img/calender.png') }}">
                            <input type="text" name="ship_from_date" id="form" placeholder="Form" class="form-control light-placeholder custom-text-input" value="{{ $request->query('ship_from_date') }}">
                        </div>
                    </div>
                </div>
                <div class="col-3">
                    <div class="form-group">
                        <label>Date To</label>
                        <div class="calender-outer">
                            <img class="user-img" src="{{ asset('img/calender.png') }}">
                            <input type="text" name="ship_to_date" id="to" placeholder="To" class="form-control light-placeholder custom-text-input" value="{{ $request->query('ship_to_date') }}">
                        </div>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label>Tracking Id</label>
                        <input type="text" name="tracking_number" placeholder="#Tracking Id" class="form-control light-placeholder custom-text-input" value="{{ $request->query('tracking_number') }}">
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label>Carrier</label>
                        <select name="carrier" class="form-control light-placeholder custom-text-input">
                            <option value="">Select Carrier</option>
                            <option value="ups" {{ $request->query('carrier') == 'ups' ? 'selected' : ''}}>UPS</option>
                            <option value="fedex" {{ $request->query('carrier') == 'fedex' ? 'selected' : ''}}>FEDEX</option>
                        </select>
                    </div>
                </div>
                <div class="col-2">
                    <div class="form-group">
                        <label>Status</label>
                        <select name="status" class="form-control light-placeholder custom-text-input">
                            <option value="">Select Status</option>
                            @foreach(config('constants.SHIPMENT_STATUS') as $key => $value)
                                <option value="{{ $key }}" {{ $request->query('status') == $key ? 'selected' : ''}}>{{ $value }}</option>
                            @endforeach
                            {{-- <option value="Intransit" {{ $request->query('status') == 'Intransit' ? 'selected' : ''}}>In Transit</option>
                            <option value="Delivered" {{ $request->query('status') == 'Delivered' ? 'selected' : ''}}>Delivered</option> --}}
                        </select>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <div class="form-group">
                        <label>Address From</label>
                        <input type="text" name="address_from" placeholder="Enter Location" class="form-control light-placeholder custom-text-input" value="{{ $request->query('address_from') }}">
                    </div>
                </div>                
                <div class="col-3">
                    <div class="form-group">
                        <label>Address To</label>
                        <input type="text" name="address_to" placeholder="Enter Location" class="form-control light-placeholder custom-text-input" value="{{ $request->query('address_to') }}">
                    </div>
                </div>                
            </div>
            <div class="row align-items-center">                
                <div class="col-4 ml-auto text-right">
                    <button class="btn btn-search" type="submit">Search Now</button>
                    <button type="reset" class="btn-reset">Clear all</button>
                </div>
            </div>
        </form>
    </div>
    <div class="db-custom-table">
        <table class="table">
            <thead>
                <tr>
                    <th>Origin destination</th>
					<th>Tracking Number</th>
                    <th>Ship Date</th>
                    <th>Carrier</th>
                    <th>Order Id</th>
                    <!-- <th>Tracking Id</th> -->
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
				@if (count($shipments))
					@foreach ($shipments as $shipment)
						<tr>
							<td>
								<ul class="location-list">
									<li>From: {{ $shipment->postal_from }}, {{ $shipment->city_from }}, CA</li>
									<li>{{ $shipment->postal_to }}, {{ $shipment->city_to }} CA </li>
								</ul>
							</td>
							<td>{{ $shipment->identification_number }}</td>
							<td>{{ $shipment->formatted_ship_date }}</td>
							<td>{{ strtoupper($shipment->carrier) }}</td>
							<td>
                                <a href="{{ route('user.order.summary', base64_encode($shipment->id)) }}">SDV-{{ $shipment->ref_code }}</a>
                            </td>
							<!-- <td>								
                                @foreach ($shipment->shipmentPackageResults as $key => $package)
                                <a href="#" class="link-text-color">
                                    <small>Package #{{ $key + 1}} {{ $package->tracking_number }}</small><br>
                                </a>
                                @endforeach
							</td> -->
							<td>
								{{ config('constants.SHIPMENT_STATUS')[$shipment->status] ?? ''}}
							</td>
						</tr>
					@endforeach
				@else
					<tr>
						<td colspan="6">{{__('No Record Found')}}</td></tr>
					</tr>
				@endif
            </tbody>
        </table>       
    </div>
</div>
@endsection

@push('scripts')
    <script>
        $(function() {
            $("#form").datepicker();
        });
        $(function() {
            $("#to").datepicker();
        });
    </script>
@endpush