routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect(route('home'));
});

Auth::routes(['verify' => true]);

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

/*
*	Admin Route
*/
Route::prefix('admin')
	->name('admin.')
	->middleware(['role:admin'])
	->group(function() {
		Route::get('/', function(){
			return view('auth.login');
		})
		->name('login')
		->middleware('guest');

		Route::get('/dashboard',[App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard.index');
		Route::resource('users', App\Http\Controllers\Admin\UserController::class)->only([
			'index', 'show','destroy'
		]);
		Route::resource('profile', App\Http\Controllers\Admin\ProfileController::class)->only([
			'create','store'
		]);
		Route::resource('change-password',App\Http\Controllers\Admin\ChangePasswordController::class)->only([
			'index', 'store'
		]);
		Route::resource('agents', App\Http\Controllers\Admin\AgentController::class);

		// Assign user to agent
		Route::get('agents/{user}/assign-user', [App\Http\Controllers\Admin\AssignUserController::class, 'create'])->name('agent-assign-user');
		Route::post('agents/{user}/assign-user/store', [App\Http\Controllers\Admin\AssignUserController::class, 'store'])->name('store-agent-assign-user');
	});

Route::prefix('user')
	->name('user.')
	->middleware(['auth', 'role:user'])
	->group(function() {
		Route::resource('change-password',App\Http\Controllers\User\ChangePasswordController::class)->only([
			'index', 'store'
		]);
		Route::resource('profile', App\Http\Controllers\User\ProfileController::class)->only([
			'create','store'
		]);
		Route::resource('dashboard', App\Http\Controllers\User\DashboardController::class)->only([
			'index'
		]);
		Route::resource('account-settings', App\Http\Controllers\User\AccountSettingController::class)->only([
			'create', 'store'
		]);
		Route::resource('order-preferences', App\Http\Controllers\User\OrderPreferenceController::class)->only([
			'index', 'create' ,'store', 'update', 'edit', 'destroy'
		]);

		Route::resource('address-book-list', App\Http\Controllers\User\AddressBookController::class)->only([
			'index', 'store', 'update', 'edit', 'destroy'
		]);
		
		Route::get('get-states-list', [App\Http\Controllers\User\CountryController::class, 'getStates'])->name('states.list');
		
		Route::get('get-cities-list', [App\Http\Controllers\User\CountryController::class, 'getCities'])->name('cities.list');

		Route::resource('products', App\Http\Controllers\User\ProductController::class)->only([
			'index','store','edit','update'
		]);

		Route::resource('manage-cards', App\Http\Controllers\User\ManageCardController::class)->only([
			'index','store','edit','update'
		]);
		
		Route::delete('order-preference-ref/{id}', [App\Http\Controllers\User\OrderReferenceController::class, 'destroy']);

		Route::delete('order-preference-broker/{id}', [App\Http\Controllers\User\OrderBrokerController::class, 'destroy']);
		
		//Letter
		Route::get('letter-quote/create', [App\Http\Controllers\User\LetterQuoteController::class, 'create'])->name('letter-quote.create');
		Route::post('letter-quote', [App\Http\Controllers\User\LetterQuoteController::class, 'store'])->name('letter-quote.store');

		//PAK
		Route::get('pak-quote/create', [App\Http\Controllers\User\PakQuoteController::class, 'create'])->name('pak-quote.create');
		Route::post('pak-quote', [App\Http\Controllers\User\PakQuoteController::class, 'store'])->name('pak-quote.store');
		
		//PACKAGE
		Route::get('package-quote/create', [App\Http\Controllers\User\PackageController::class, 'create'])->name('package-quote.create');
		Route::post('package-quote', [App\Http\Controllers\User\PackageController::class, 'store'])->name('package-quote.store');

		//Get shipment rates
		Route::post('get-shipment-rates', [App\Http\Controllers\User\ShipmentRateController::class, 'getRates'])->name('shipment-rates');		
		Route::post('set-shipment-rate', [App\Http\Controllers\User\ShipmentRateController::class, 'setShipmentRate'])->name('shipment.set.rate');

		//Checkout
		Route::get('shipment-checkout', [App\Http\Controllers\User\ShipmentRateController::class, 'checkout'])->name('shipment.checkout');
		Route::post('shipment-checkout', [App\Http\Controllers\User\CheckoutController::class, 'store'])->name('checkout');

		//Order Summary page
		Route::get('order-summary/{id}', [App\Http\Controllers\User\OrderController::class, 'show'])->name('order.summary');

		//My Shipemensts List
		Route::get('my-shipments', [App\Http\Controllers\User\MyShipmentController::class, 'index'])->name('my.shipments');
	});

/**
 * Agent routes 
 */
Route::prefix('agent')->name('agent.')->group(function() {
	Route::get('/', function() {
		return view('auth.login');
	})
	->name('login')
	->middleware('guest');

	Route::get('/dashboard',[App\Http\Controllers\Agent\DashboardController::class,'index'])
	->name('dashboard.index')
	->middleware(['auth', 'role:agent']);

	Route::get('/assigned-user',[App\Http\Controllers\Agent\AssignedUserController::class,'index'])
	->name('assigned-user.index')
	->middleware(['auth', 'role:agent']);

	Route::get('/assigned-user/create',[App\Http\Controllers\Agent\AssignedUserController::class,'create'])
	->name('assigned-user.create')
	->middleware(['auth', 'role:agent']);

	Route::post('/assigned-user/store',[App\Http\Controllers\Agent\AssignedUserController::class,'store'])
	->name('store-agent-assign-user')
	->middleware(['auth', 'role:agent']);
});

Route::prefix('agent')->name('agent.')->middleware(['auth', 'role:agent,user'])->group(function() {
	Route::post('/login-as-customer', [App\Http\Controllers\Agent\AssignedUserController::class,'loginAsCustomer'])->name('login-as-customer')->middleware(['auth']);
});

Route::get('/signup', function () {
	return view('pages.signup');
});

Route::get('/forget-password', function () {
	return view('pages.forget-password');
});

Route::get('/address-book', function () {
	return view('pages.address-book');
});

Route::get('/distributions', function () {
	return view('pages.distributions');
});

Route::get('/add-product', function () {
	return view('pages.add-product');
});

Route::get('/account-settings-page', function () {
	return view('pages.account-settings');
});

Route::get('/home-page', function () {
	return view('pages.home');
});


Route::get('/my-shipment-all', function () {
	return view('pages.my-shipment-all');
});

Route::get('/active-shipment', function () {
	return view('pages.active-shipment');
});

Route::get('/delivered-shipment', function () {
	return view('pages.delivered-shipment');
});

Route::get('/my-quote', function () {
	return view('pages.my-quote');
});

Route::get('/my-quote-list', function () {
	return view('pages.my-quote-list');
});

Route::get('/choose-packaging', function () {
	return view('pages.choose-packaging');
});

Route::get('/letter', function () {
	return view('pages.letter');
});

Route::get('/pak', function () {
	return view('pages.pak');
});

Route::get('/package', function () {
	return view('pages.package');
});

Route::get('/ltl', function () {
	return view('pages.ltl');
});

// Fedex
Route::get('sample-fedex', [App\Http\Controllers\FedExController::class, 'store']);
Route::get('sample-ltl-fedex', [App\Http\Controllers\FedExController::class, 'ltl']);

// Create pending FedEx shipment
Route::get('create-fedex-open-shipment', [App\Http\Controllers\FedExController::class, 'createOpenShipment']);

// UPS get single rate
Route::get('get-ups-rate', [App\Http\Controllers\UpsController::class, 'store']);

// UPS get service rates 
Route::get('get-ups-transit-rate', [App\Http\Controllers\UpsController::class, 'rateTimeInTransit']);

Route::get('create-ups-shipment', [App\Http\Controllers\UpsController::class, 'createShipment']);

// Canada Post rating
Route::get('get-canada-post-rate', [App\Http\Controllers\CanadaPostController::class, 'getRates']);

//Create Quote home page

Route::post('request-quote/create', [App\Http\Controllers\RequestQuoteController::class, 'store'])->name('request.quote.create');

/*
//Courier canpar API demo
// Route::get('courier/canpar-api-tracking', [App\Http\Controllers\CourierApiController::class, 'canparApiCourierTracking']);

//Courier ArcBest API demo
// Route::get('courier/arc-best-api-get-rates', [App\Http\Controllers\CourierApiController::class, 'arcbestapiGetRates']);

//Canada Post API sandbox rates between 2 points
// Route::get('courier/canada-post-api-get-rates-two-points', [App\Http\Controllers\CourierApiController::class, 'canadaPostApiGetRates']);
*/

//AutoComplete city
Route::get('search-cities-suggestions', [App\Http\Controllers\CitySearchController::class, 'searchCity'])->name('autocomplete.city');

//Import Excel
Route::get('import-excel', [App\Http\Controllers\ImportExcelController::class, 'index'])->name('import.list');
Route::post('import-excel', [App\Http\Controllers\ImportExcelController::class, 'store'])->name('import.excel.store');

//Track UPS Shipment
Route::get('track-ups-shipment/{trackId}', [App\Http\Controllers\UpsController::class, 'trackShipment']);
Route::get('cancel-ups-shipment/{shipmentid}', [App\Http\Controllers\UpsController::class, 'cancelShipment']);

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\User;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        $users = User::where([ 
            'role_id' =>2 
        ])->withTrashed()->paginate(15);

        return view('admin.user.index',compact('users'));
    }

    public function show($id)
    {
        $user = User::withTrashed()->find($id);
        return view('admin.user.show',compact('user'));

    }

    public function destroy($id)
    {
        $user = User::withTrashed()->find($id);
        $message='deleted';
        if ($user->trashed()) {
            $user->restore();
            $message='restored';
        } else {
            $user->delete();
        }

        return back()
            ->with('success', "User has been $message successfully.");
    }
}

app/Http/Controllers/User/AccountSettingController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserProfile;
use App\Models\CompanyDetail;
use App\Models\Country;
use App\Models\Language;
use App\Models\Unit;
use App\Models\NotificationSetting;
use App\Models\OrderPreference;
use Illuminate\Support\Facades\Auth;
use App\Models\UserCard;
use App\Models\AccountPayableDetail;
use Stripe\Stripe;
use Stripe\Customer;
use Stripe\Charge;
use Exception;

class AccountSettingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $publishkey = config('app.STRIPE_PUBLISHABLE_KEY');

        $user = User::where(['id' => Auth::user()->id])->first();

        //Country
        $countries = Country::get(['name', 'id']);

        //Languages
        $languages = Language::pluck('title', 'id');

        //Units
        $units = Unit::pluck('title', 'id');

        //Notifications
        $userId = Auth::user()->id;
        
        //Nitification Settings
        $notificationSettings = NotificationSetting::pluck('title', 'id');

        //Order Preferences        
        $orders = OrderPreference::where('user_id', $userId)->get();

        //My Cards
        $myCards = UserCard::where('user_id', Auth::user()->id)->get();

        return view('user.settings.account.create', compact(
            'user', 
            'countries', 
            'units', 
            'languages', 
            'orders', 
            'notificationSettings',
            'publishkey',
            'myCards'
        ));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $id = Auth::user()->id;

        $request->validate([
            'first_name' => 'required|string',
            'last_name'  => 'required|string',
            'email'      => 'required|string|unique:users,email,'.$id,
            'phone_number'=> 'required|string',
            'company_name' => 'required|string',
            'address' => 'required|string',
            'postal_code' => 'required|string',
            'company_email' => 'required|string|email',
            'company_phone' => 'required|string',
            'company_country' => 'required',
            'company_state' => 'required',
            'company_city' => 'required|string|max:255',
            'billing_address' => 'required|string|max:255',
            'billing_country' => 'required|string|max:255',
            'billing_state' => 'required|string|max:255',
            'billing_city' => 'required|string|max:255',
            'billing_postal_code' => 'required|string|max:255',
            'billing_email' => 'required|string|max:255',
            'billing_phone' => 'required|string|max:255',
            'contact_name' => 'required|string',
            'account_payable_email' => 'required|string|email',
            'account_payable_phone' => 'required|string',
            'payment_terms' => 'required|string'
        ]);

        $input = $request->all();

        $user = User::find($id);

        $user->email = $input['email'];

        $user->save();

        //Profile
        $user->profile()->updateOrCreate(['user_id' => $id], [
            'first_name' => $input['first_name'],
            'last_name' => $input['last_name'],
            'phone_no' => $input['full_phone'],
        ]);

        //Account Payable Details
        $user->accountPayableDetail()->updateOrCreate(['user_id' => $id], [
            'contact_name' => $input['contact_name'],
            'email' => $input['account_payable_email'],
            'phone' => $input['account_payable_phone'],
            'payment_terms' => $input['payment_terms'],
            'is_prepaid' => (int) $request->has('is_prepaid'),
            'is_same_main_contact' => (int) $request->has('is_same_main_contact'),
        ]);

        //Billing Address
        $user->billingAddress()->updateOrCreate(['user_id' => $id], [
            'address' => $input['billing_address'],
            'country' => $input['billing_country'],
            'state' => $input['billing_state'],
            'city' => $input['billing_city'],
            'postal_code' => $input['billing_postal_code'],
            'email' => $input['billing_email'],
            'phone_no' => $input['billing_phone'],
        ]);

        //Company Information
        $user->companyDetail()->updateOrCreate(['user_id' => $id], [
            'company_name' => $input['company_name'],
            'address' => $input['address'],
            'postal_code' => $input['postal_code'],
            'email' => $input['company_email'],
            'phone_no' => $input['company_phone'],
            'country_id' => $input['company_country'],
            'state_id' => $input['company_state'],
            'city' => $input['company_city'],
            'is_bill_same' => (int) $request->has('is_bill_same')
        ]);

        //Notification Settings
        $user->notificationSettings()->sync($request->notificationSettings);

        return redirect()->back()->with('message', "Account settings has been updated successfully.");
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/User/DashboardController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth','verified']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.dashboard.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
}

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('title', 'Users')
@section('content')
  	<section>
        <div class="container-fluid">
          	<!-- Page Header-->
          	<header> 
          		<div class="row">
          			<div class="col-md-8">
            			<h2 class="h3 display">{{__(strtoupper('Users'))}}</h2>
          			</div>
          			<div class="col-md-4 text-right">
          			</div>
          		</div>
          		<!-- alert message component -->
            	<x-alert/>	
          	</header>
			  <div class="row">
            	<div class="col">
                    <div class="table-responsive">
                        <table class="table">
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Phone Number</th>
                                <th>Action</th>
                            </tr>
                            @foreach ($users as $user)
                                <tr>
                                    <td>{{$loop->index+1}}</td>
                                    <td>{{$user->profile->full_name ?? ''}}</td> 
                                    <td>{{$user->email}}</td>
                                    <td>{{$user->profile->phone_no ?? ''}}</td>
                                    <td class="d-flex">
                                        @if(!$user->deleted_at)
                                            <form action="{{ route('admin.users.destroy',$user->id)}}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }} 
                                                <a href="#">
                                                    <i class="fa fa-trash" data-message="deactivate">
                                                        Deactivate
                                                    </i>
                                                </a>
                                            </form>
                                        @else
                                            <form action="{{ route('admin.users.destroy',$user->id) }}" method="POST">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }} 
                                                <a href="#">
                                                    <i class="fa fa-undo text-danger" data-message="restore">
                                                        Restore
                                                    </i>
                                                </a>
                                            </form>
                                        @endif
                                        <a class="ml-3" href="{{ route('admin.users.show', [ 'user'=> $user->id ]) }}" >
                                            <i class="fa fa-eye"></i> View
                                        </a>
                                    </td>
                                </tr>
                            @endforeach
                        </table>
                    </div>
                </div>
          	</div>
          	
        </div>
  	</section>
@endsection

@push('scripts')
	<script type="text/javascript">
		$('.fa-trash, .fa-undo').on('click', function(e){
			let msg = $(this).attr('data-message');
			let form = $(this).closest('form');
			if(confirm(`Are you sure want to ${msg} the user`)) {
				form.submit();
			}
		});
	</script>	
@endpush;

resources/views/admin/user/show.blade.php
@extends('layouts.admin')

@section('content')
    <section>
        <div class="container-fluid">
            <!-- Page Header-->
            <header> 
                <div class="row">
                    <div class="col-md-6">
                        <h1 class="">{{ __('View Details') }}</h1>
                    </div>
                    <div class="col-md-6 text-right">
                        <a href="{{route('admin.users.index')}}" class="btn btn-blue">
                            Back
                        </a>
                    </div>
                </div>
                @if (session('status'))
                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                        {{ session('status') }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                @endif
                <x-alert/>	
            </header>
            <div class="row">
			<!-- /.col-->
			<div class="col-lg-8">
				<div class="card">
					<div class="card-header">Account Information</div>
					<div class="card-body">						
						<div class="bd-example">
							<dl class="row">
								<dt class="col-sm-2">Name</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->profile)
                                        ?
                                            $user->profile->full_name
                                        :"N/A"
                                    }}									
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Email</dt>
								<dd class="col-sm-10">
									{{  ($user->email) }}									
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Phone Number</dt>
								<dd class="col-sm-10">
									{{  ($user->profile->phone_no) }}									
								</dd>															
                            </dl>
						</div>												
                    </div>
                    <div class="card-header">Company Information</div>
					<div class="card-body">						
						<div class="bd-example">
							<dl class="row">
								<dt class="col-sm-2">Company Name</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->company_name
                                        :"N/A"
                                    }}									
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Address</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->address
                                        :"N/A"
                                    }}								
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Phone Number</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->phone_no
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Email</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->email
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Country</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->country->name
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">State</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->state->name
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">City</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->city
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Postal Code</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->companyDetail)
                                        ?
                                            $user->companyDetail->postal_code
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
						</div>												
                    </div>
                    
                    <div class="card-header">Billing Information</div>
					<div class="card-body">						
						<div class="bd-example">							
                            <dl class="row">
								<dt class="col-sm-2">Address</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->address
                                        :"N/A"
                                    }}								
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Phone Number</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->phone_no
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Email</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->email
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Country</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->country
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">State</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->state
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">City</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->city
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
                            <dl class="row">
								<dt class="col-sm-2">Postal Code</dt>
								<dd class="col-sm-10">
									{{ 
                                        ($user->billingAddress)
                                        ?
                                            $user->billingAddress->postal_code
                                        :"N/A"
                                    }}										
								</dd>															
                            </dl>
						</div>												
					</div>
				</div>
			</div>
			<!-- /.col-->
		</div>
        </div>
    </section>
@endsection